kumuluzee:
  name: upravljanje_profilov-service
  version: 1.0.0
  env:
    name: dev

  server:
      base-url: http://localhost:8080
      http:
        port: 8080

  config:
    start-retry-delay-ms: 500
    max-retry-delay-ms: 900000
    etcd:
      hosts: http://192.168.99.100:2379

  discovery:
    etcd:
      hosts: http://192.168.99.100:2379
    ttl: 20
    ping-interval: 15

rest-endpoints:
  naziv-dogodka: Konfiguracija